// apps/web/src/components/workflow/WorkflowMonitor.tsx

import { useState, useEffect, useCallback } from 'react';
import { Activity, Server, Pause, Play, RotateCcw, Trash2 } from 'lucide-react';
import { useWorkflowSSE } from '@/hooks/useWorkflowSSE';
import { Card } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { workflowApi, type WorkflowStats } from '@/lib/workflow-api';
import type { WorkflowEvent } from '@/lib/sse-client';
import { useToast } from '@/lib/toast';

interface WorkflowMonitorProps {
  className?: string;
  autoRefresh?: boolean;
  refreshInterval?: number;
}

export function WorkflowMonitor({ 
  className = '',
  autoRefresh = true,
  refreshInterval = 30000 
}: WorkflowMonitorProps) {
  const toast = useToast();
  const [stats, setStats] = useState<WorkflowStats | null>(null);
  const [systemHealth, setSystemHealth] = useState<{
    redis: boolean;
    queues: { publisher: boolean };
    processors: { publisher: boolean };
  } | null>(null);
  const [isLoading, setIsLoading] = useState(true);
  const [recentEvents, setRecentEvents] = useState<WorkflowEvent[]>([]);

  // Handle workflow events
  const handleWorkflowEvent = useCallback((event: WorkflowEvent) => {
    setRecentEvents(prev => {
      const newEvents = [event, ...prev.slice(0, 9)]; // Keep last 10 events
      return newEvents;
    });
  }, []);

  // SSE connection for real-time events
  const { isConnected } = useWorkflowSSE(handleWorkflowEvent, autoRefresh);

  // Fetch stats and health
  const fetchData = useCallback(async () => {
    try {
      const [statsResponse, healthResponse] = await Promise.all([
        workflowApi.system.getStats(),
        workflowApi.system.getHealth()
      ]);

      if (statsResponse.success) {
        setStats(statsResponse.data || null);
      }

      if (healthResponse.success) {
        setSystemHealth(healthResponse.data || null);
      }
    } catch (error) {
      console.error('Failed to fetch workflow data:', error);
    } finally {
      setIsLoading(false);
    }
  }, []);

  // System control actions
  const pauseAllProcessing = useCallback(async () => {
    try {
      const response = await workflowApi.system.pauseAll();
      if (response.success) {
        toast.success('All processing paused');
        fetchData();
      } else {
        toast.error('Failed to pause processing: ' + response.error);
      }
    } catch (error) {
      toast.error('Failed to pause processing');
    }
  }, [toast, fetchData]);

  const resumeAllProcessing = useCallback(async () => {
    try {
      const response = await workflowApi.system.resumeAll();
      if (response.success) {
        toast.success('All processing resumed');
        fetchData();
      } else {
        toast.error('Failed to resume processing: ' + response.error);
      }
    } catch (error) {
      toast.error('Failed to resume processing');
    }
  }, [toast, fetchData]);

  const clearCompletedJobs = useCallback(async () => {
    try {
      const response = await workflowApi.system.clearCompleted();
      if (response.success) {
        toast.success('Completed jobs cleared');
        fetchData();
      } else {
        toast.error('Failed to clear jobs: ' + response.error);
      }
    } catch (error) {
      toast.error('Failed to clear completed jobs');
    }
  }, [toast, fetchData]);

  const clearFailedJobs = useCallback(async () => {
    try {
      const response = await workflowApi.system.clearFailed();
      if (response.success) {
        toast.success('Failed jobs cleared');
        fetchData();
      } else {
        toast.error('Failed to clear jobs: ' + response.error);
      }
    } catch (error) {
      toast.error('Failed to clear failed jobs');
    }
  }, [toast, fetchData]);

  // Initial load and periodic refresh
  useEffect(() => {
    fetchData();
    
    if (autoRefresh) {
      const interval = setInterval(fetchData, refreshInterval);
      return () => clearInterval(interval);
    }
  }, [fetchData, autoRefresh, refreshInterval]);

  const getHealthStatusColor = (isHealthy: boolean) => {
    return isHealthy ? 'bg-green-500' : 'bg-red-500';
  };

  const formatEventType = (type: string) => {
    return type.replace(/[._]/g, ' ').replace(/\b\w/g, l => l.toUpperCase());
  };

  const getEventIcon = (event: WorkflowEvent) => {
    if (event.type.includes('completed')) return '✅';
    if (event.type.includes('failed')) return '❌';
    if (event.type.includes('started')) return '🚀';
    if (event.type.includes('progress')) return '⏳';
    return '📋';
  };

  if (isLoading) {
    return (
      <Card className={`p-6 ${className}`}>
        <div className="flex items-center gap-2">
          <Activity className="h-5 w-5 animate-pulse" />
          <span>Loading workflow monitor...</span>
        </div>
      </Card>
    );
  }

  return (
    <div className={`space-y-4 ${className}`}>
      {/* System Health */}
      <Card className="p-4">
        <div className="flex items-center justify-between mb-4">
          <div className="flex items-center gap-2">
            <Server className="h-5 w-5" />
            <h3 className="font-semibold">System Health</h3>
            <div className={`w-2 h-2 rounded-full ${isConnected ? 'bg-green-500' : 'bg-red-500'}`} />
          </div>
          
          <div className="flex gap-2">
            <Button
              variant="outline"
              size="sm"
              onClick={systemHealth?.processors?.publisher ? pauseAllProcessing : resumeAllProcessing}
            >
              {systemHealth?.processors?.publisher ? (
                <>
                  <Pause className="h-3 w-3 mr-1" />
                  Pause All
                </>
              ) : (
                <>
                  <Play className="h-3 w-3 mr-1" />
                  Resume All
                </>
              )}
            </Button>
            <Button variant="outline" size="sm" onClick={fetchData}>
              <RotateCcw className="h-3 w-3" />
            </Button>
          </div>
        </div>

        {systemHealth && (
          <div className="grid grid-cols-3 gap-4 text-sm">
            <div className="flex items-center gap-2">
              <div className={`w-2 h-2 rounded-full ${getHealthStatusColor(systemHealth.redis)}`} />
              <span>Redis: {systemHealth.redis ? 'Connected' : 'Disconnected'}</span>
            </div>
            <div className="flex items-center gap-2">
              <div className={`w-2 h-2 rounded-full ${getHealthStatusColor(systemHealth.queues.publisher)}`} />
              <span>Queues: {systemHealth.queues.publisher ? 'Healthy' : 'Unhealthy'}</span>
            </div>
            <div className="flex items-center gap-2">
              <div className={`w-2 h-2 rounded-full ${getHealthStatusColor(systemHealth.processors.publisher)}`} />
              <span>Processors: {systemHealth.processors.publisher ? 'Running' : 'Stopped'}</span>
            </div>
          </div>
        )}
      </Card>

      {/* Queue Statistics */}
      {stats && (
        <Card className="p-4">
          <div className="flex items-center justify-between mb-4">
            <h3 className="font-semibold">Queue Statistics</h3>
            <div className="flex gap-2">
              <Button
                variant="outline"
                size="sm"
                onClick={clearCompletedJobs}
                className="text-xs"
              >
                <Trash2 className="h-3 w-3 mr-1" />
                Clear Completed
              </Button>
              <Button
                variant="outline"
                size="sm"
                onClick={clearFailedJobs}
                className="text-xs text-red-600"
              >
                <Trash2 className="h-3 w-3 mr-1" />
                Clear Failed
              </Button>
            </div>
          </div>

          <div className="grid grid-cols-2 gap-4">
            {/* Publisher Queue */}
            <div className="space-y-2">
              <h4 className="font-medium text-sm">Publisher Queue</h4>
              <div className="grid grid-cols-2 gap-2 text-sm">
                <div className="flex justify-between">
                  <span>Waiting:</span>
                  <Badge variant="outline">{stats.publisher.queue.waiting}</Badge>
                </div>
                <div className="flex justify-between">
                  <span>Active:</span>
                  <Badge variant="outline">{stats.publisher.queue.active}</Badge>
                </div>
                <div className="flex justify-between">
                  <span>Completed:</span>
                  <Badge variant="default">{stats.publisher.queue.completed}</Badge>
                </div>
                <div className="flex justify-between">
                  <span>Failed:</span>
                  <Badge variant="destructive">{stats.publisher.queue.failed}</Badge>
                </div>
              </div>
            </div>

            {/* Content Processing Queues */}
            <div className="space-y-2">
              <h4 className="font-medium text-sm">Content Processing</h4>
              <div className="space-y-1 text-xs">
                <div className="flex items-center justify-between">
                  <span>Clean Transcript:</span>
                  <div className="flex gap-1">
                    <Badge variant="outline" className="text-xs">{stats.content.cleanTranscript.waiting}W</Badge>
                    <Badge variant="outline" className="text-xs">{stats.content.cleanTranscript.active}A</Badge>
                    <Badge variant="default" className="text-xs">{stats.content.cleanTranscript.completed}C</Badge>
                    <Badge variant="destructive" className="text-xs">{stats.content.cleanTranscript.failed}F</Badge>
                  </div>
                </div>
                <div className="flex items-center justify-between">
                  <span>Extract Insights:</span>
                  <div className="flex gap-1">
                    <Badge variant="outline" className="text-xs">{stats.content.extractInsights.waiting}W</Badge>
                    <Badge variant="outline" className="text-xs">{stats.content.extractInsights.active}A</Badge>
                    <Badge variant="default" className="text-xs">{stats.content.extractInsights.completed}C</Badge>
                    <Badge variant="destructive" className="text-xs">{stats.content.extractInsights.failed}F</Badge>
                  </div>
                </div>
                <div className="flex items-center justify-between">
                  <span>Generate Posts:</span>
                  <div className="flex gap-1">
                    <Badge variant="outline" className="text-xs">{stats.content.generatePosts.waiting}W</Badge>
                    <Badge variant="outline" className="text-xs">{stats.content.generatePosts.active}A</Badge>
                    <Badge variant="default" className="text-xs">{stats.content.generatePosts.completed}C</Badge>
                    <Badge variant="destructive" className="text-xs">{stats.content.generatePosts.failed}F</Badge>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </Card>
      )}

      {/* Recent Events */}
      <Card className="p-4">
        <div className="flex items-center gap-2 mb-4">
          <Activity className="h-4 w-4" />
          <h3 className="font-semibold">Recent Events</h3>
          <div className={`w-2 h-2 rounded-full ${isConnected ? 'bg-green-500' : 'bg-gray-400'}`} />
        </div>

        <div className="space-y-2 max-h-64 overflow-y-auto">
          {recentEvents.length === 0 ? (
            <p className="text-sm text-gray-500 text-center py-4">
              {isConnected ? 'No recent events' : 'Connect to see real-time events'}
            </p>
          ) : (
            recentEvents.map((event, index) => (
              <div
                key={index}
                className="flex items-center gap-3 p-2 bg-gray-50 rounded text-sm"
              >
                <span className="text-lg">{getEventIcon(event)}</span>
                <div className="flex-1">
                  <span className="font-medium">{formatEventType(event.type)}</span>
                  {'jobId' in event && (
                    <span className="text-gray-500 ml-2">Job: {event.jobId.slice(-8)}</span>
                  )}
                  {'transcriptId' in event && (
                    <span className="text-gray-500 ml-2">Transcript: {event.transcriptId.slice(-8)}</span>
                  )}
                </div>
                <span className="text-xs text-gray-500">
                  {new Date(event.timestamp).toLocaleTimeString()}
                </span>
              </div>
            ))
          )}
        </div>
      </Card>
    </div>
  );
}

// apps/web-angular/src/app/shared/components/workflow-monitor/workflow-monitor.component.ts
import { Component, OnInit, OnDestroy, inject, signal, computed, Input, ChangeDetectionStrategy } from '@angular/core';
import { CommonModule } from '@angular/common';
import { interval, Subscription } from 'rxjs';
import { WorkflowService, WorkflowStats, SystemHealth } from '../../../core/services/workflow.service';
import { SSEService, WorkflowEvent } from '../../../core/services/sse.service';

@Component({
  selector: 'app-workflow-monitor',
  standalone: true,
  imports: [CommonModule],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <div [class]="'bg-white rounded-lg shadow-md ' + className">
      <!-- Header -->
      <div class="px-6 py-4 border-b border-gray-200">
        <div class="flex items-center justify-between">
          <div class="flex items-center space-x-3">
            <div class="flex items-center">
              <i class="pi pi-server text-2xl text-gray-700 mr-2"></i>
              <h3 class="text-lg font-semibold text-gray-800">Workflow System Monitor</h3>
            </div>
            <!-- Connection Status -->
            <div class="flex items-center space-x-2">
              <div 
                class="w-2 h-2 rounded-full animate-pulse"
                [class.bg-green-500]="isConnected()"
                [class.bg-red-500]="!isConnected()"
              ></div>
              <span class="text-xs text-gray-500">
                {{ isConnected() ? 'Connected' : 'Disconnected' }}
              </span>
            </div>
          </div>
          
          <!-- Control Buttons -->
          <div class="flex items-center space-x-2">
            <button
              (click)="toggleAutoRefresh()"
              class="px-3 py-1 text-sm border rounded-lg transition-colors"
              [class.bg-blue-50]="autoRefresh"
              [class.border-blue-300]="autoRefresh"
              [class.text-blue-700]="autoRefresh"
              [class.bg-gray-50]="!autoRefresh"
              [class.border-gray-300]="!autoRefresh"
              [class.text-gray-700]="!autoRefresh"
            >
              <i class="pi pi-refresh mr-1"></i>
              Auto-refresh {{ autoRefresh ? 'ON' : 'OFF' }}
            </button>
            <button
              (click)="fetchData()"
              class="px-3 py-1 text-sm bg-gray-100 hover:bg-gray-200 border border-gray-300 rounded-lg transition-colors"
            >
              <i class="pi pi-sync"></i>
            </button>
          </div>
        </div>
      </div>
      
      <!-- System Health -->
      <div class="px-6 py-4 border-b border-gray-200" *ngIf="systemHealth()">
        <div class="flex items-center justify-between">
          <h4 class="text-sm font-medium text-gray-700">System Health</h4>
          <div class="flex items-center space-x-4">
            <div class="flex items-center">
              <div 
                class="w-2 h-2 rounded-full mr-2"
                [class.bg-green-500]="systemHealth()?.redis"
                [class.bg-red-500]="!systemHealth()?.redis"
              ></div>
              <span class="text-sm text-gray-600">Redis</span>
            </div>
            <div class="flex items-center">
              <div 
                class="w-2 h-2 rounded-full mr-2"
                [class.bg-green-500]="systemHealth()?.queues?.publisher"
                [class.bg-red-500]="!systemHealth()?.queues?.publisher"
              ></div>
              <span class="text-sm text-gray-600">Publisher Queue</span>
            </div>
            <div class="flex items-center">
              <div 
                class="w-2 h-2 rounded-full mr-2"
                [class.bg-green-500]="systemHealth()?.processors?.publisher"
                [class.bg-red-500]="!systemHealth()?.processors?.publisher"
              ></div>
              <span class="text-sm text-gray-600">Publisher Processor</span>
            </div>
          </div>
        </div>
      </div>
      
      <!-- Loading State -->
      <div *ngIf="isLoading()" class="px-6 py-8 text-center">
        <i class="pi pi-spin pi-spinner text-3xl text-gray-400"></i>
        <p class="mt-2 text-gray-500">Loading workflow stats...</p>
      </div>
      
      <!-- Stats Grid -->
      <div *ngIf="!isLoading() && stats()" class="p-6">
        <!-- Queue Stats -->
        <div class="mb-6">
          <h4 class="text-sm font-medium text-gray-700 mb-3">Queue Statistics</h4>
          <div class="grid grid-cols-2 md:grid-cols-4 gap-4">
            <div class="bg-gray-50 rounded-lg p-3">
              <div class="flex items-center justify-between">
                <span class="text-xs text-gray-500">Active</span>
                <i class="pi pi-play text-green-500"></i>
              </div>
              <p class="text-2xl font-bold text-gray-800 mt-1">{{ stats()?.jobs?.active || 0 }}</p>
            </div>
            <div class="bg-gray-50 rounded-lg p-3">
              <div class="flex items-center justify-between">
                <span class="text-xs text-gray-500">Waiting</span>
                <i class="pi pi-clock text-yellow-500"></i>
              </div>
              <p class="text-2xl font-bold text-gray-800 mt-1">{{ stats()?.jobs?.waiting || 0 }}</p>
            </div>
            <div class="bg-gray-50 rounded-lg p-3">
              <div class="flex items-center justify-between">
                <span class="text-xs text-gray-500">Completed</span>
                <i class="pi pi-check-circle text-green-500"></i>
              </div>
              <p class="text-2xl font-bold text-gray-800 mt-1">{{ stats()?.jobs?.completed || 0 }}</p>
            </div>
            <div class="bg-gray-50 rounded-lg p-3">
              <div class="flex items-center justify-between">
                <span class="text-xs text-gray-500">Failed</span>
                <i class="pi pi-times-circle text-red-500"></i>
              </div>
              <p class="text-2xl font-bold text-gray-800 mt-1">{{ stats()?.jobs?.failed || 0 }}</p>
            </div>
          </div>
        </div>
        
        <!-- Performance Metrics -->
        <div class="mb-6">
          <h4 class="text-sm font-medium text-gray-700 mb-3">Performance</h4>
          <div class="grid grid-cols-1 md:grid-cols-3 gap-4">
            <div class="bg-blue-50 rounded-lg p-3">
              <span class="text-xs text-blue-600">Jobs/Minute</span>
              <p class="text-xl font-bold text-blue-800 mt-1">
                {{ stats()?.performance?.jobsPerMinute?.toFixed(1) || '0' }}
              </p>
            </div>
            <div class="bg-purple-50 rounded-lg p-3">
              <span class="text-xs text-purple-600">Avg Processing Time</span>
              <p class="text-xl font-bold text-purple-800 mt-1">
                {{ formatDuration(stats()?.performance?.avgProcessingTime || 0) }}
              </p>
            </div>
            <div class="bg-green-50 rounded-lg p-3">
              <span class="text-xs text-green-600">Success Rate</span>
              <p class="text-xl font-bold text-green-800 mt-1">
                {{ (stats()?.performance?.successRate || 0) * 100 | number:'1.0-0' }}%
              </p>
            </div>
          </div>
        </div>
        
        <!-- Control Actions -->
        <div class="mb-6">
          <h4 class="text-sm font-medium text-gray-700 mb-3">System Controls</h4>
          <div class="flex flex-wrap gap-2">
            <button
              (click)="pauseAllProcessing()"
              class="px-3 py-1.5 bg-yellow-100 hover:bg-yellow-200 text-yellow-800 rounded-lg text-sm transition-colors flex items-center"
            >
              <i class="pi pi-pause mr-1"></i>
              Pause All
            </button>
            <button
              (click)="resumeAllProcessing()"
              class="px-3 py-1.5 bg-green-100 hover:bg-green-200 text-green-800 rounded-lg text-sm transition-colors flex items-center"
            >
              <i class="pi pi-play mr-1"></i>
              Resume All
            </button>
            <button
              (click)="retryFailed()"
              class="px-3 py-1.5 bg-blue-100 hover:bg-blue-200 text-blue-800 rounded-lg text-sm transition-colors flex items-center"
            >
              <i class="pi pi-refresh mr-1"></i>
              Retry Failed
            </button>
            <button
              (click)="clearCompleted()"
              class="px-3 py-1.5 bg-gray-100 hover:bg-gray-200 text-gray-800 rounded-lg text-sm transition-colors flex items-center"
            >
              <i class="pi pi-trash mr-1"></i>
              Clear Completed
            </button>
            <button
              (click)="clearFailed()"
              class="px-3 py-1.5 bg-red-100 hover:bg-red-200 text-red-800 rounded-lg text-sm transition-colors flex items-center"
            >
              <i class="pi pi-trash mr-1"></i>
              Clear Failed
            </button>
          </div>
        </div>
        
        <!-- Recent Events -->
        <div *ngIf="recentEvents().length > 0">
          <h4 class="text-sm font-medium text-gray-700 mb-3">Recent Events</h4>
          <div class="bg-gray-50 rounded-lg p-3 max-h-48 overflow-y-auto">
            <div 
              *ngFor="let event of recentEvents()"
              class="flex items-start space-x-2 py-1.5 border-b border-gray-200 last:border-0"
            >
              <span class="text-lg">{{ getEventIcon(event) }}</span>
              <div class="flex-1 min-w-0">
                <p class="text-sm text-gray-800">
                  {{ formatEventType(event.type) }}
                </p>
                <p class="text-xs text-gray-500">
                  {{ formatEventTime(event.timestamp) }}
                </p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  `,
  styles: []
})
export class WorkflowMonitorComponent implements OnInit, OnDestroy {
  @Input() className = '';
  @Input() autoRefresh = true;
  @Input() refreshInterval = 30000; // 30 seconds
  
  private workflowService = inject(WorkflowService);
  private sseService = inject(SSEService);
  
  // State signals
  stats = signal<WorkflowStats | null>(null);
  systemHealth = signal<SystemHealth | null>(null);
  isLoading = signal(true);
  recentEvents = signal<WorkflowEvent[]>([]);
  isConnected = signal(false);
  
  // Subscriptions
  private refreshSubscription?: Subscription;
  private sseConnection?: any;
  
  ngOnInit(): void {
    this.fetchData();
    this.setupSSEConnection();
    
    if (this.autoRefresh) {
      this.startAutoRefresh();
    }
  }
  
  ngOnDestroy(): void {
    this.stopAutoRefresh();
    if (this.sseConnection) {
      this.sseConnection.cleanup();
    }
  }
  
  fetchData(): void {
    this.isLoading.set(true);
    
    // Fetch stats and health in parallel
    Promise.all([
      this.workflowService.getStats().toPromise(),
      this.workflowService.getHealth().toPromise()
    ]).then(([statsResult, healthResult]) => {
      if (statsResult?.success) {
        this.stats.set(statsResult.data || null);
      }
      if (healthResult?.success) {
        this.systemHealth.set(healthResult.data || null);
      }
      this.isLoading.set(false);
    }).catch(error => {
      console.error('Failed to fetch workflow data:', error);
      this.isLoading.set(false);
    });
  }
  
  setupSSEConnection(): void {
    this.sseConnection = this.sseService.createWorkflowSSEConnection(
      (event) => {
        // Add to recent events
        const events = this.recentEvents();
        this.recentEvents.set([event, ...events.slice(0, 9)]); // Keep last 10
      },
      (error) => {
        console.error('SSE connection error:', error);
        this.isConnected.set(false);
      },
      () => {
        console.log('SSE connection established');
        this.isConnected.set(true);
      }
    );
  }
  
  toggleAutoRefresh(): void {
    this.autoRefresh = !this.autoRefresh;
    if (this.autoRefresh) {
      this.startAutoRefresh();
    } else {
      this.stopAutoRefresh();
    }
  }
  
  startAutoRefresh(): void {
    this.stopAutoRefresh();
    this.refreshSubscription = interval(this.refreshInterval).subscribe(() => {
      this.fetchData();
    });
  }
  
  stopAutoRefresh(): void {
    if (this.refreshSubscription) {
      this.refreshSubscription.unsubscribe();
      this.refreshSubscription = undefined;
    }
  }
  
  pauseAllProcessing(): void {
    this.workflowService.pauseAll().subscribe(result => {
      if (result.success) {
        console.log('All processing paused');
        this.fetchData();
      }
    });
  }
  
  resumeAllProcessing(): void {
    this.workflowService.resumeAll().subscribe(result => {
      if (result.success) {
        console.log('All processing resumed');
        this.fetchData();
      }
    });
  }
  
  retryFailed(): void {
    this.workflowService.retryFailed().subscribe(result => {
      if (result.success) {
        console.log('Failed jobs retried:', result.data);
        this.fetchData();
      }
    });
  }
  
  clearCompleted(): void {
    this.workflowService.clearCompleted().subscribe(result => {
      if (result.success) {
        console.log('Completed jobs cleared:', result.data);
        this.fetchData();
      }
    });
  }
  
  clearFailed(): void {
    this.workflowService.clearFailed().subscribe(result => {
      if (result.success) {
        console.log('Failed jobs cleared:', result.data);
        this.fetchData();
      }
    });
  }
  
  formatDuration(ms: number): string {
    if (ms < 1000) return `${ms}ms`;
    if (ms < 60000) return `${(ms / 1000).toFixed(1)}s`;
    return `${(ms / 60000).toFixed(1)}m`;
  }
  
  formatEventType(type: string): string {
    return type.replace(/[._]/g, ' ').replace(/\b\w/g, l => l.toUpperCase());
  }
  
  formatEventTime(timestamp: string): string {
    const date = new Date(timestamp);
    return date.toLocaleTimeString();
  }
  
  getEventIcon(event: WorkflowEvent): string {
    if (event.type.includes('completed')) return '✅';
    if (event.type.includes('failed')) return '❌';
    if (event.type.includes('started')) return '🚀';
    if (event.type.includes('progress')) return '⏳';
    if (event.type.includes('blocked')) return '🚧';
    return '📋';
  }
}
