// apps/web/resources/js/Pages/Projects/components/PostEditor.vue
<script setup>
import { formatDateTime, formatRelativeTime } from '@/utils/datetime';
import { computed } from 'vue';
import { useHashtags } from '../composables/useHashtags';
import { Button } from '@/components/ui/button';

const props = defineProps({
  post: { type: Object, default: null },
  content: { type: String, default: '' },
  hashtags: { type: Array, default: () => [] },
  statusOptions: { type: Array, default: () => [] },
  editorSaving: { type: Boolean, default: false },
  postDirty: { type: Boolean, default: false },
  linkedInConnected: { type: Boolean, default: false },
  isAutoScheduling: { type: Boolean, default: false },
  isUnscheduling: { type: Boolean, default: false },
});

const emit = defineEmits([
  'update:content',
  'update:hashtags',
  'changeStatus',
  'openWorkbench',
  'openRegenerate',
  'save',
  'scheduleOpen',
  'publishNow',
  'unschedulePost',
  'autoSchedulePost',
  'clearHashtags',
]);

const contentModel = computed({
  get: () => props.content,
  set: (v) => emit('update:content', v),
});

const hashtagsModel = computed({
  get: () => props.hashtags,
  set: (v) => emit('update:hashtags', v),
});

const {
  hashtagsInputRef,
  hashtagSuggestions,
  handleHashtagKeydown,
  handleHashtagBlur,
  handleHashtagPaste,
  handleHashtagComplete,
} = useHashtags(hashtagsModel);
</script>

<template>
  <div class="flex min-h-[360px] flex-col rounded-md border border-zinc-200 bg-white p-4">
    <div class="flex items-center justify-between gap-2">
      <div class="hidden sm:flex">
        <label class="sr-only" for="post-status">Status</label>
        <select
          id="post-status"
          :value="post?.status ?? 'pending'"
          @change="(e) => { const val = e.target.value; if (val && val !== 'published' && post) emit('changeStatus', val); }"
          class="rounded-md border border-zinc-300 bg-white px-2 py-1 text-sm shadow-sm focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-zinc-900"
        >
          <option v-for="opt in statusOptions" :key="opt.value" :value="opt.value" :disabled="opt.disabled">{{ opt.label }}</option>
        </select>
      </div>
      <div class="flex items-center gap-2">
        <Button size="sm" variant="outline" :disabled="!post" @click="() => emit('openWorkbench')">Hook Workbench</Button>
        <Button size="sm" variant="secondary" :disabled="!post" @click="() => emit('openRegenerate')">Regenerate</Button>
      </div>
    </div>
    <div class="mt-3 flex-1">
      <textarea
        :value="contentModel"
        @input="(e) => contentModel = e.target.value"
        rows="10"
        class="w-full rounded-md border border-zinc-300 px-3 py-2 text-sm shadow-sm focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-zinc-900"
        placeholder="Edit post content…"
        @keydown="(e) => { if ((e.metaKey || e.ctrlKey) && e.key === 'Enter' && !editorSaving && post && postDirty) { e.preventDefault(); emit('save'); } }"
      />
      <div class="mt-2 flex items-center justify-between text-xs text-zinc-600">
        <span class="tabular-nums text-zinc-500">{{ (content || '').length }}/3000</span>
        <Button size="sm" variant="secondary" :disabled="!post || editorSaving || !postDirty" @click="() => emit('save')">Save</Button>
      </div>
    </div>
    <div class="mt-3">
      <div class="mb-1 flex items-center justify-between">
        <label class="block text-sm font-medium text-zinc-800">Hashtags</label>
        <Button size="sm" variant="outline" :disabled="!post || (hashtags?.length ?? 0) === 0" @click="() => emit('clearHashtags')">Clear hashtags</Button>
      </div>
      <input
        ref="hashtagsInputRef"
        type="text"
        placeholder="#hashtag"
        class="w-full rounded-md border border-zinc-300 px-3 py-2 text-sm shadow-sm focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-zinc-900"
        @keydown="handleHashtagKeydown"
        @blur="handleHashtagBlur"
        @paste="handleHashtagPaste"
      />
      <div class="mt-2 flex flex-wrap gap-2">
        <span v-for="tag in hashtagsModel" :key="tag" class="inline-flex items-center gap-1 rounded-full bg-zinc-100 px-2 py-0.5 text-xs text-zinc-700">
          #{{ tag }}
          <Button
            variant="ghost"
            size="sm"
            class="ml-1 h-5 w-5 p-0 text-zinc-500 hover:text-zinc-900"
            aria-label="Remove hashtag"
            @click="() => { hashtagsModel = hashtagsModel.filter((t) => t !== tag); }"
          >
            ×
          </Button>
        </span>
      </div>
    </div>

    <div class="mt-4 flex flex-wrap items-center gap-2 justify-end">
      <Button size="sm" :disabled="!post || post.status!=='approved' || editorSaving || !linkedInConnected" @click="() => emit('scheduleOpen')">Schedule</Button>
      <Button size="sm" variant="secondary" :disabled="!post || post.status!=='approved' || editorSaving || isAutoScheduling || !linkedInConnected" @click="() => emit('autoSchedulePost')">Auto-schedule</Button>
      <Button size="sm" :disabled="!post || post.status!=='approved' || editorSaving" @click="() => emit('publishNow')">Publish Now</Button>
    </div>

    <div v-if="post" class="mt-3 text-xs text-zinc-600">
      <div v-if="post.publishedAt">Published at {{ formatDateTime(post.publishedAt) }}</div>
      <div v-else-if="post.scheduledAt" class="flex items-center gap-2">
        <span>Scheduled for {{ formatDateTime(post.scheduledAt) }}</span>
        <Button size="sm" variant="outline" :disabled="isUnscheduling" @click="() => emit('unschedulePost')">Unschedule</Button>
      </div>
      <div v-else class="text-zinc-500">Not scheduled</div>
      <!-- Auto-retry hint for failed scheduling -->
      <div v-if="post.scheduleStatus === 'failed'" class="mt-1 text-zinc-600">
        <template v-if="post.scheduleNextAttemptAt">
          <span>Retrying {{ formatRelativeTime(post.scheduleNextAttemptAt) }} (at {{ formatDateTime(post.scheduleNextAttemptAt) }})</span>
          <span v-if="post.scheduleAttempts && post.scheduleAttempts > 0"> · attempt {{ post.scheduleAttempts }}</span>
          <span v-if="post.scheduleError"> · last error: {{ post.scheduleError }}</span>
        </template>
        <template v-else>
          <span>Scheduling failed</span>
          <span v-if="post.scheduleError">: {{ post.scheduleError }}</span>
          <span>. Update settings or reschedule to try again.</span>
        </template>
      </div>
    </div>
  </div>
</template>

// apps/web/src/components/project/PostEditor.tsx
import React, { useEffect, useState } from 'react'
import { Card, CardContent, CardHeader } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { ToggleGroup, ToggleGroupItem } from '@/components/ui/toggle-group'
import { Textarea } from '@/components/ui/textarea'
import type { Post, PostStatus } from '@content/shared-types'
import HashtagEditor from './HashtagEditor'
import ScheduleDialog from './ScheduleDialog'
import ScheduleSummary from './ScheduleSummary'
import type { ScheduleInfo } from './utils'
import { isModerationStatus, isPromiseLike } from './utils'

export default function PostEditor({
  post,
  linkedInConnected,
  onSave,
  onSetStatus,
  onPublish,
  onSchedule,
  onUnschedule,
  onAutoSchedule,
  isScheduling,
  isUnscheduling,
  isAutoScheduling,
  onRegenerate,
}: {
  post: Post | null
  linkedInConnected: boolean
  onSave: (content: string, hashtags: string[]) => Promise<void> | void
  onSetStatus: (status: PostStatus) => void
  onPublish: () => void
  onSchedule: (date: Date) => Promise<void>
  onUnschedule: () => Promise<void>
  onAutoSchedule: () => Promise<void>
  isScheduling: boolean
  isUnscheduling: boolean
  isAutoScheduling: boolean
  onRegenerate: () => void
}) {
  const hasPost = Boolean(post)
  const [content, setContent] = useState(hasPost ? post!.content : '')
  const [hashtags, setHashtags] = useState<string[]>(hasPost ? post!.hashtags : [])
  const [baseContent, setBaseContent] = useState(hasPost ? post!.content : '')
  const [baseTags, setBaseTags] = useState<string[]>(hasPost ? post!.hashtags : [])
  const [saving, setSaving] = useState(false)
  useEffect(() => {
    if (!post) return
    setContent(post.content)
    setHashtags(post.hashtags)
    setBaseContent(post.content)
    setBaseTags(post.hashtags)
  }, [post?.id, post?.content, JSON.stringify(post?.hashtags || [])])

  const dirty = content !== baseContent || JSON.stringify(hashtags) !== JSON.stringify(baseTags)

  const canSchedule = hasPost && post!.status === 'approved' && linkedInConnected
  const scheduleInfo = (hasPost
    ? {
        scheduledAt: post!.scheduledAt ?? null,
        status: post!.scheduleStatus ?? null,
        error: post!.scheduleError ?? null,
        attemptedAt: post!.scheduleAttemptedAt ?? null,
        postStatus: post!.status,
        publishedAt: post!.publishedAt ?? null,
      }
    : {
        scheduledAt: null,
        status: null,
        error: null,
        attemptedAt: null,
        postStatus: 'pending' as PostStatus,
        publishedAt: null,
      }) as ScheduleInfo
  const isPublishing = scheduleInfo.status === 'publishing'
  const actionsBlocked = dirty || saving
  const scheduleDisabledReason = !canSchedule
    ? hasPost && post!.status === 'published'
      ? 'Post already published'
      : 'Approve the post and connect LinkedIn before scheduling'
    : actionsBlocked
      ? 'Save changes before scheduling'
      : undefined
  const publishDisabled = !canSchedule || actionsBlocked || isScheduling || isUnscheduling || isPublishing

  const handleSave = async () => {
    if (!dirty || saving) return
    setSaving(true)
    try {
      const maybe = onSave(content.slice(0, 3000), hashtags)
      if (isPromiseLike<void>(maybe)) await maybe
      setBaseContent(content)
      setBaseTags(hashtags)
    } finally {
      setSaving(false)
    }
  }

  return (
    <Card className="h-full overflow-hidden flex flex-col">
      <CardHeader>
        <div className="flex items-center justify-between gap-2">
          <div className="flex items-center gap-2">
            <span className="font-medium text-zinc-900">
              {hasPost ? `Post #${post!.id}` : 'Select a post to edit'}
            </span>
          </div>
          <div className="flex items-center gap-2">
            {hasPost && (
              <div className="hidden sm:flex">
                <ToggleGroup
                  type="single"
                  value={post!.status}
                  onValueChange={(value) => isModerationStatus(value) && onSetStatus(value)}
                >
                  <ToggleGroupItem value="pending">Pending</ToggleGroupItem>
                  <ToggleGroupItem value="approved">Approved</ToggleGroupItem>
                  <ToggleGroupItem value="rejected">Rejected</ToggleGroupItem>
                  <ToggleGroupItem value="published" disabled>
                    Published
                  </ToggleGroupItem>
                </ToggleGroup>
              </div>
            )}
            <Button size="sm" variant="secondary" onClick={onRegenerate} disabled={saving || !hasPost}>
              Regenerate
            </Button>
          </div>
        </div>
      </CardHeader>
      <CardContent className="flex-1 flex flex-col overflow-hidden space-y-6">
        <div className="flex-1 min-h-0">
          <Textarea
            className="h-full w-full bg-white border-zinc-200 focus-visible:ring-zinc-300 overflow-auto resize-none"
            value={content}
            onChange={(e) => setContent(e.target.value)}
            />
          <div className="mt-2 flex items-center justify-between text-xs text-zinc-600">
            <span className="tabular-nums text-zinc-500">{content.length}/3000</span>
            <div className="flex items-center gap-2">
              {!dirty && !saving && hasPost && <span className="text-zinc-500">Saved</span>}
              <Button size="sm" variant="secondary" disabled={!hasPost || !dirty || saving} onClick={handleSave}>
                {saving ? 'Saving…' : 'Save'}
              </Button>
            </div>
          </div>
        </div>
        <HashtagEditor value={hashtags} onChange={setHashtags} />
        <div className="flex items-center gap-2 flex-wrap justify-end">
          <ScheduleDialog
            disabled={!hasPost || !canSchedule || actionsBlocked}
            triggerTitle={scheduleDisabledReason}
            scheduleInfo={scheduleInfo}
            onSchedule={onSchedule}
            onUnschedule={onUnschedule}
            isScheduling={isScheduling}
            isUnscheduling={isUnscheduling}
          />
          <div className="hidden sm:flex items-center gap-2">
            <Button
              size="sm"
              variant="secondary"
              disabled={!hasPost || !canSchedule || actionsBlocked || isAutoScheduling}
              title={scheduleDisabledReason}
              onClick={() => onAutoSchedule()}
            >
              {isAutoScheduling ? 'Auto-scheduling…' : 'Auto-schedule'}
            </Button>
            <Button
              size="sm"
              variant="default"
              disabled={!hasPost || publishDisabled}
              title={
                dirty
                  ? 'Please save changes before publishing'
                  : publishDisabled && (isScheduling || isUnscheduling)
                    ? 'Please wait for scheduling to complete'
                    : publishDisabled && isPublishing
                      ? 'Publishing in progress'
                      : undefined
              }
              onClick={onPublish}
            >
              Publish Now
            </Button>
          </div>
        </div>
        {hasPost && <ScheduleSummary info={scheduleInfo} />}
      </CardContent>
    </Card>
  )
}
