// apps/web/resources/js/Pages/Analytics/Index.vue
<script setup>
import AppLayout from '@/Layouts/AppLayout.vue';
import { Head } from '@inertiajs/vue3';
import { computed } from 'vue';

const props = defineProps({
    summary: {
        type: Object,
        required: true,
        // { totalPosts, statusCounts: {pending, approved, rejected, published}, scheduledCount, publishedInPeriod, averageTimeToPublishHours|null, rangeDays }
    },
    daily: {
        type: Array,
        required: true,
        // [{ date: 'YYYY-MM-DD', published: number }]
    },
    topHashtags: {
        type: Array,
        default: () => [],
        // [{ tag: string, count: number }]
    },
});

const numberFormatter = new Intl.NumberFormat(undefined, { maximumFractionDigits: 0 });
const decimalFormatter = new Intl.NumberFormat(undefined, { minimumFractionDigits: 1, maximumFractionDigits: 1 });

const averageLabel = computed(() => {
    const v = props.summary?.averageTimeToPublishHours;
    if (v === null || typeof v === 'undefined') return '—';
    try { return `${decimalFormatter.format(v)} hrs`; } catch { return `${v}`; }
});

const recentDaily = computed(() => {
    const list = Array.isArray(props.daily) ? props.daily : [];
    const count = Math.min(14, list.length);
    return count > 0 ? list.slice(-count) : [];
});

const formatDate = (value) => {
    if (!value) return '';
    try {
        return new Intl.DateTimeFormat(undefined, { month: 'short', day: 'numeric', year: 'numeric' }).format(new Date(value));
    } catch { return value; }
};

const statusMeta = [
    { key: 'pending', label: 'Pending review', tone: 'muted' },
    { key: 'approved', label: 'Approved', tone: 'default' },
    { key: 'rejected', label: 'Rejected', tone: 'muted' },
    { key: 'published', label: 'Published', tone: 'default' },
];
</script>

<template>
    <AppLayout title="Analytics">
        <Head title="Analytics" />
        <div class="space-y-6">
            <div>
                <h2 class="text-2xl font-semibold text-zinc-900">Analytics</h2>
                <p class="text-sm text-zinc-600">Track how your LinkedIn posts are performing over the last {{ summary.rangeDays }} days.</p>
            </div>

            <section class="grid gap-4 md:grid-cols-2 xl:grid-cols-4">
                <div class="rounded-lg border border-zinc-200 bg-white p-4 shadow-sm">
                    <div class="text-sm font-medium text-zinc-500">Total posts</div>
                    <div class="mt-1 text-2xl font-semibold text-zinc-900">{{ numberFormatter.format(summary.totalPosts ?? 0) }}</div>
                </div>
                <div class="rounded-lg border border-zinc-200 bg-white p-4 shadow-sm">
                    <div class="text-sm font-medium text-zinc-500">Published (last {{ summary.rangeDays }} days)</div>
                    <div class="mt-1 text-2xl font-semibold text-zinc-900">{{ numberFormatter.format(summary.publishedInPeriod ?? 0) }}</div>
                </div>
                <div class="rounded-lg border border-zinc-200 bg-white p-4 shadow-sm">
                    <div class="text-sm font-medium text-zinc-500">Scheduled</div>
                    <div class="mt-1 text-2xl font-semibold text-zinc-900">{{ numberFormatter.format(summary.scheduledCount ?? 0) }}</div>
                </div>
                <div class="rounded-lg border border-zinc-200 bg-white p-4 shadow-sm">
                    <div class="text-sm font-medium text-zinc-500">Avg. time to publish</div>
                    <div class="mt-1 text-2xl font-semibold text-zinc-900">{{ averageLabel }}</div>
                </div>
            </section>

            <section class="grid gap-4 lg:grid-cols-2">
                <div class="rounded-lg border border-zinc-200 bg-white p-4 shadow-sm">
                    <h3 class="text-base font-medium text-zinc-900">Status breakdown</h3>
                    <div class="mt-3 space-y-3">
                        <div v-for="item in statusMeta" :key="item.key" class="flex items-center justify-between text-sm">
                            <div class="flex items-center gap-2">
                                <span
                                    class="inline-flex items-center rounded-full border px-2.5 py-1 text-xs font-medium uppercase tracking-wide"
                                    :class="item.tone === 'muted' ? 'border-zinc-300 text-zinc-700' : 'border-zinc-900 bg-zinc-900 text-white'"
                                >
                                    {{ item.label }}
                                </span>
                            </div>
                            <span class="font-medium text-zinc-900">{{ numberFormatter.format(summary.statusCounts?.[item.key] ?? 0) }}</span>
                        </div>
                    </div>
                </div>

                <div class="rounded-lg border border-zinc-200 bg-white p-4 shadow-sm">
                    <h3 class="text-base font-medium text-zinc-900">Top hashtags</h3>
                    <div class="mt-3">
                        <p v-if="(topHashtags?.length ?? 0) === 0" class="text-sm text-zinc-600">
                            No hashtags yet. Add hashtags to your posts to see trends.
                        </p>
                        <div v-else class="overflow-x-auto">
                            <table class="min-w-full text-left text-sm">
                                <thead>
                                    <tr class="text-zinc-600">
                                        <th scope="col" class="w-16 px-3 py-2 font-medium">#</th>
                                        <th scope="col" class="px-3 py-2 font-medium">Hashtag</th>
                                        <th scope="col" class="px-3 py-2 text-right font-medium">Posts</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr v-for="(item, index) in topHashtags" :key="item.tag" class="border-t border-zinc-200">
                                        <td class="px-3 py-2 font-medium text-zinc-900">{{ index + 1 }}</td>
                                        <td class="px-3 py-2 text-zinc-800">#{{ String(item.tag || '').replace(/^#+/, '') }}</td>
                                        <td class="px-3 py-2 text-right">{{ numberFormatter.format(item.count ?? 0) }}</td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </section>

            <section class="rounded-lg border border-zinc-200 bg-white p-4 shadow-sm">
                <h3 class="text-base font-medium text-zinc-900">Publishing cadence</h3>
                <div class="mt-3">
                    <p v-if="recentDaily.length === 0" class="text-sm text-zinc-600">No published posts in this period.</p>
                    <div v-else class="overflow-x-auto">
                        <table class="min-w-full text-left text-sm">
                            <thead>
                                <tr class="text-zinc-600">
                                    <th scope="col" class="px-3 py-2 font-medium">Date</th>
                                    <th scope="col" class="px-3 py-2 text-right font-medium">Published</th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr v-for="entry in recentDaily" :key="entry.date" class="border-t border-zinc-200">
                                    <td class="px-3 py-2 text-zinc-800">{{ formatDate(entry.date) }}</td>
                                    <td class="px-3 py-2 text-right font-medium">{{ numberFormatter.format(entry.published ?? 0) }}</td>
                                </tr>
                            </tbody>
                        </table>
                        <p class="mt-3 text-xs text-zinc-500">Showing the most recent {{ recentDaily.length }} days within this window.</p>
                    </div>
                </div>
            </section>
        </div>
    </AppLayout>
    
</template>

// apps/web/src/routes/analytics.tsx
import { createFileRoute, redirect } from '@tanstack/react-router'
import { format } from 'date-fns'
import { getSession } from '@/lib/session'
import * as postsClient from '@/lib/client/posts'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table'
import { Badge } from '@/components/ui/badge'

const numberFormatter = new Intl.NumberFormat(undefined, { maximumFractionDigits: 0 })
const decimalFormatter = new Intl.NumberFormat(undefined, { minimumFractionDigits: 1, maximumFractionDigits: 1 })

function SummaryCard({
  title,
  value,
  description,
}: {
  title: string
  value: string
  description?: string
}) {
  return (
    <Card>
      <CardHeader className="pb-2">
        <CardTitle className="text-sm font-medium text-zinc-500">{title}</CardTitle>
      </CardHeader>
      <CardContent className="pt-0">
        <div className="text-2xl font-semibold text-zinc-900">{value}</div>
        {description ? <p className="text-xs text-zinc-500 mt-1">{description}</p> : null}
      </CardContent>
    </Card>
  )
}

function AnalyticsPage() {
  const data = Route.useLoaderData() as Awaited<ReturnType<typeof postsClient.getAnalytics>>
  const { summary, daily, topHashtags } = data
  const recentDaily = daily.slice(-Math.min(14, daily.length))
  const averageLabel =
    summary.averageTimeToPublishHours === null
      ? '—'
      : `${decimalFormatter.format(summary.averageTimeToPublishHours)} hrs`

  const statusMeta: Array<{ key: keyof typeof summary.statusCounts; label: string; tone: 'default' | 'muted' }>
    = [
      { key: 'pending', label: 'Pending review', tone: 'muted' },
      { key: 'approved', label: 'Approved', tone: 'default' },
      { key: 'rejected', label: 'Rejected', tone: 'muted' },
      { key: 'published', label: 'Published', tone: 'default' },
    ]

  return (
    <div className="p-6 space-y-6">
      <div>
        <h1 className="text-2xl font-semibold text-zinc-900">Analytics</h1>
        <p className="text-sm text-zinc-600">
          Track how your LinkedIn posts are performing over the last {summary.rangeDays} days.
        </p>
      </div>

      <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">
        <SummaryCard title="Total posts" value={numberFormatter.format(summary.totalPosts)} />
        <SummaryCard
          title={`Published (last ${summary.rangeDays} days)`}
          value={numberFormatter.format(summary.publishedInPeriod)}
        />
        <SummaryCard title="Scheduled" value={numberFormatter.format(summary.scheduledCount)} />
        <SummaryCard title="Avg. time to publish" value={averageLabel} />
      </div>

      <div className="grid gap-4 lg:grid-cols-2">
        <Card>
          <CardHeader>
            <CardTitle className="text-base font-medium">Status breakdown</CardTitle>
          </CardHeader>
          <CardContent className="space-y-3">
            {statusMeta.map((item) => {
              const value = summary.statusCounts[item.key]
              return (
                <div key={item.key} className="flex items-center justify-between text-sm">
                  <div className="flex items-center gap-2">
                    <Badge variant={item.tone === 'muted' ? 'outline' : 'default'} className="uppercase tracking-wide">
                      {item.label}
                    </Badge>
                  </div>
                  <span className="font-medium text-zinc-900">{numberFormatter.format(value)}</span>
                </div>
              )
            })}
          </CardContent>
        </Card>

        <Card>
          <CardHeader>
            <CardTitle className="text-base font-medium">Top hashtags</CardTitle>
          </CardHeader>
          <CardContent>
            {topHashtags.length === 0 ? (
              <p className="text-sm text-zinc-600">No hashtags yet. Add hashtags to your posts to see trends.</p>
            ) : (
              <Table>
                <TableHeader>
                  <TableRow>
                    <TableHead className="w-16">#</TableHead>
                    <TableHead>Hashtag</TableHead>
                    <TableHead className="text-right">Posts</TableHead>
                  </TableRow>
                </TableHeader>
                <TableBody>
                  {topHashtags.map((item, index) => (
                    <TableRow key={item.tag}>
                      <TableCell className="font-medium">{index + 1}</TableCell>
                      <TableCell className="text-zinc-800">#{item.tag.replace(/^#+/, '')}</TableCell>
                      <TableCell className="text-right">
                        {numberFormatter.format(item.count)}
                      </TableCell>
                    </TableRow>
                  ))}
                </TableBody>
              </Table>
            )}
          </CardContent>
        </Card>
      </div>

      <Card>
        <CardHeader>
          <CardTitle className="text-base font-medium">Publishing cadence</CardTitle>
        </CardHeader>
        <CardContent>
          {recentDaily.length === 0 ? (
            <p className="text-sm text-zinc-600">No published posts in this period.</p>
          ) : (
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead>Date</TableHead>
                  <TableHead className="text-right">Published</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {recentDaily.map((entry) => (
                  <TableRow key={entry.date}>
                    <TableCell className="text-zinc-800">
                      {format(new Date(entry.date), 'MMM d, yyyy')}
                    </TableCell>
                    <TableCell className="text-right font-medium">
                      {numberFormatter.format(entry.published)}
                    </TableCell>
                  </TableRow>
                ))}
              </TableBody>
            </Table>
          )}
          {recentDaily.length > 0 ? (
            <p className="text-xs text-zinc-500 mt-3">
              Showing the most recent {recentDaily.length} days within this window.
            </p>
          ) : null}
        </CardContent>
      </Card>
    </div>
  )
}

export const Route = createFileRoute('/analytics')({
  beforeLoad: async () => {
    try {
      await getSession()
    } catch {
      throw redirect({ to: '/login' })
    }
  },
  loader: async () => postsClient.getAnalytics(),
  pendingComponent: () => (
    <div className="p-6">
      <h1 className="text-2xl font-semibold mb-2">Analytics</h1>
      <p className="text-sm text-zinc-600">Loading analytics…</p>
    </div>
  ),
  component: AnalyticsPage,
})
